---
title: "R and ChatGPT (3/3)"
description: |
  Improve your R skills in entertaining, inspiring and supportive sessions moderated by your own colleagues.
author:
  - name: Abby Onencan
    url: https://www.eur.nl/en/people/abby-onencan
date: 04-30-2024
output:
  distill::distill_article:
    self_contained: false
---

The NSC-R Tidy Tuesday workshop sessions are inspired by the 
[Tidy Tuesday](https://www.tidytuesday.com/) initiative, which is aimed at 
providing a safe and supportive forum for individuals to practice their data processing 
and visualization skills in R while working with real-world data.

This workshop (Tuesday April 30, 2024, 13:00-14:00 CET) was the last in a series of three 
about the use of ChatGPT in R. Together the three workshops form a beginners' 
course on how to integrate ChatGPT when working with R. They were led by Abby Onencan.

**The previous workshops in this course are on Monday April 2 and on Monday April 15, 13:00-14:00**. 

A complete description of all three sessions is in 
[our post of April 2](https://nscrweb.netlify.app/posts/2024-04-02-nsc-r-tidy-tuesday/)


> *Abby Onencan* is a researcher at the Erasmus School of Law at Erasmus University Rotterdam. Her research focuses on industrial environmental harms, specifically those resulting from the production and use of PFAS. She is a member of the NSC-R Workshops team.

### Materials

To consult the materials used in this third session, please

 1.    Open RStudio
 2.    Create a new R project named "GPTAutomation" and include the files from 
  [this folder](https://nscrweb.netlify.app/materials/2024-04-30-nsc-r-workshop-chatgpt_3/GPTAutomation.zip) (ZIP archive) or from
  [this folder](https://nscrweb.netlify.app/materials/2024-04-30-nsc-r-workshop-chatgpt_3/GPTAutomation.rar) (RAR archive). Both are compressed archives and contain the same files. Use whichever is more convenient.
3. Install the listed packages (in the new R project) and set the API key. The packages are
"shiny", "shiny.i18n", "shinyjs", "openai", "httr", "jsonlite", "chatgpt", "askgpt", and "gptstudio".


