---
title: "Using GitHub for version control, collaboration and code sharing."
description: |
  A workshop on using GitHub for version control, collaboration and code sharing.
author: 
  - name: Harrie Jonkman
    url: www.harriejonkman.nl/
date: 11-25-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Version control is essential for keeping track of data analysis projects. It is also essential for collaboration with other researchers and developers. 

**Git**, **GitHub** in combination with **R/RStudio** allow you to back up texts and scripts and to collaborate on complex projects. Git and GitHub are open source version control systems which work quiet well together with R/RStudio. 

This workshop introduced this system, demonstrated how to create a repository on GitHub, and how to do this from R/RStudio (see [Harrie's presentation (PDF)](VersioncontrolGit.pdf)). 

The workshop also included a live demonstration of how collaboration between multiple people works in a simple repository/project. 

The workshop was connected to the subsequent workshop in which the new NSC-R Workshop website was be presented (the one you are reading now). This website is developed by the NSC-R team members who worked together on this in Git, GitHub and R/RStudio.  

### More information

Below are links to potentially usefull sources about Git, Github and their integration with R/RStudio.

- Douglas, A., Roos, D., Mancini, F., Couto, A. and Lusseau, D., *An introduction to R*, chapter 9, [here](https://intro2r.com/github_r.html). 

- Bryan, J., *Happy Git and GitHub for the useR*, [here](https://happygitwithr.com/)

- Lendway, L., *github_for_collaboration*, [here](https://github.com/llendway/github_for_collaboration)


### Lisa Lendway on YouTube

- [Using Git and GitHub in R Studio](https://www.youtube.com/watch?v=QLFc9gw_Hfs)

- [Using Git and GitHub in R](https://www.youtube.com/watch?v=megZYkCLMA4)




> [Harrie Jonkman](https://www.harriejonkman.nl)is a senior researcher at the [Verwey Jonker Institute](https://www.verwey-jonker.nl/). He works in the field of cognitive and social development of children and youngsters in relation to the contexts in which they grow up (family, school, friends, community and country). Recently he edited with David Farrington and Frederick Groeger-Roth [Delinquency and Substance Use in Europe. Understanding Risk and Protective Factors](https://link.springer.com/book/10.1007/978-3-030-58442-9). He also finished recently the open-source book [Terugschrijven](http://www.harriejonkman.nl/wp-content/uploads/2021/05/Terugschrijven_def.pdf) on knowledge, development and democracy. He is interested in open-source data analysis and has his blog [Harrie's Hoekje](http://www.harriejonkman.nl/HarriesHoekje/) on this topic.



