---
title: "Extra material"
site: distill::distill_website
---

## On Learning R  

Batra, N. (ed, 2021). *The Epidemiologist R Handbook*. [here](https://epirhandbook.com/index.html)

Baumer, B.S., Kaplan, D.T. & Horton, N.J. (2018). *Modern Data Science with R*. Boca Raton: CRC Press. 

Grolemund, G. & Wickham, H. (2019). *R for Data Science*. [here](https://r4ds.had.co.nz/) 

Irizarry, R.A. (2019). *Introduction to Data Science. Data Analysis and Prediction Algorithms with R*. [here](https://rafalab.github.io/dsbook/) 

Kaplan, J. (2021). Crime by the Numbers: A Criminologist's Guide to R. [here](https://crimebythenumbers.com/)

## On Reproducibility

Gandrud, C. *Reproducible Research with R and RStudio, Second edition*. [here](https://radhakrishna.typepad.com/reproducible-research-with-r-and-rstudio---second-edition.pdf) 

Navarro, D. (2019). *Learning statistics with R: A tutorial for psychology students and other beginners*. [here](https://learningstatisticswithr.com/book/)

## On RMarkdown
Xie, Y., Allaire, J.J. & Grolemund, G.(2019). *R Markdown: The Definitive Guide*. [here](https://bookdown.org/yihui/rmarkdown/) 

Xie, Y., Dervieux, C. & Riederer, E. (2021). *RMarkdown Cookbook*. [here(https://bookdown.org/yihui/rmarkdown-cookbook/)


## On Spatial data
Lovelace, R., Nowosad, J. & Muenchow, J. (2021, this version). *Geocomputation with R*. [here](https://geocompr.robinlovelace.net/)

## On Open data


## On Spatial regression


## On Tidyverse
Grolemund, G. & Wickham, H. (2019). *R for Data Science*. [here](https://r4ds.had.co.nz/) 

## On crime forecasting


## On small area estimation


## On Git, GitHub and R/RStudio

Douglas, A., Roos, D., Mancini, F., Couto, A. and Lusseau, D., *An introduction to R*, chapter 9, [here](https://intro2r.com/github_r.html). Thank you.

Bryan, J., *Happy Git and GitHub for the useR*, [here](https://happygitwithr.com/)

Lendway, L., *github_for_collaboration*, [here](https://github.com/llendway/github_for_collaboration)

On youtube, [here](https://www.youtube.com/watch?v=QLFc9gw_Hfs)

On youtube also, [here](https://www.youtube.com/watch?v=megZYkCLMA4)

## On distill

Liza Lendways nice description, [here](https://lisalendway.netlify.app/posts/2020-12-09-buildingdistill/?utm_source=dlvr.it&utm_medium=facebook)


Different steps, [here](https://themockup.blog/posts/2020-08-01-building-a-blog-with-distill/)

RStduio's official website link, [here](https://rstudio.github.io/distill/)

RStduio's neww developements on distill,[here](https://www.rstudio.com/blog/distill/)


Workshop on distill you find, [here](https://rstudio.github.io/distill/)
















--