---
title: "Tidy Tuesday Workshop"
description: |
  Improve your R skills in entertaining, inspiring and supportive sessions moderated by your own colleagues.
author:
  - name: Sam Langton
    url: https://www.samlangton.info/
date: 01-09-2024
output:
  distill::distill_article:
    self_contained: false
---

The NSC-R Tidy Tuesday workshop sessions are inspired by the [Tidy Tuesday](https://www.tidytuesday.com/) initiative, which is aimed at providing a safe and supportive forum for individuals to practice their data processing and visualization skills in R while working with real-world data.

This workshop (January 9, 2024, 13:00-14:00) will be led by Sam Langton. Sam will be exploring data scraped from the BBC news website on the 'most read' stories of the day. Please join us on January 9, 2024 at 13:00 CET on Zoom by clicking [here](https://us02web.zoom.us/j/4539912989)  using password *NSCR*.


> *Sam Langton* is a postdoc researcher on the evidence-based policing programme at the NSCR. His research focuses on describing and explaining the spatial and temporal patterning of police demand. Sam is interested in promoting open science in criminology, particularly through open data and sharing his knowledge (and struggles) in R.

### Materials

The materials for the workshop are available on the [GitHub repository](https://github.com/langtonhugh/bbc_scrape). The workshop will more or less follow the script named `tidytuesday_9jan2024.R` using the `tt_subset.csv` dataset in the data folder.
