---
title: "NSC-R Tidy Tuesday"
description: |
  Improve your R skills in entertaining, inspiring and supportive sessions moderated by your own colleagues.
author:
  - name: Alex Trinidad
    url: https://www.alexandertrinidad.com/
date: 06-06-2023
output:
  distill::distill_article:
    self_contained: false
---
The NSC-R Tidy Tuesday workshop sessions are inspired by the [Tidy Tuesday](https://www.tidytuesday.com/) initiative, which is aimed at providing a safe and supportive forum for individuals to practice their data processing and visualization skills in R while working with real-world data. 

In this workshop (June 6, 2023, 13:00-14:00), Alex Trinidad will discuss how to do regression diagnostrics in R. 

Join this hybrid workshop in the NSCR Colloquium Room or online on Zoom [here](https://us02web.zoom.us/j/81879726248?pwd=UHZ1SXZHZHdHQWpyZE1WOVE3dDQvQT09)


> **Alex Trinidad** is a postdoctoral researcher and lecturer at the Institute of Sociology and Social Psychology (ISS) at the University of Cologne, and a research fellow for the Crime Events in Context research group at the NSCR and for the Crim-Ap research group at the University of the Basque Country UPV/EHU. He is also a member of the NSC-R Workshops Team.


### Materials

Materials will be posted here online after the workshop.
