---
title: "Simulation"
description: |
  Learn how to use simulation in R.
author:
  - name: Lisa DeBruine
    url: https://debruine.github.io/
date: 12-06-2022
output:
  distill::distill_article:
    self_contained: false

---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

In this workshop, **Lisa DeBruine** will show how you can use R to conduct simulations.

This session will cover the basics of simulation using the R package `faux`. We will simulate data with factorial designs by specifying the within and between-subjects factor structure, each cell mean and standard deviation, and correlations between cells where appropriate. This can be used to create simulated data sets to be used in preparing the analysis code for pre-registrations or registered reports. We will also create data sets for simulation-based power analyses. Participants will need to have very basic knowledge of R and R Markdown, and have installed `faux`, `afex`, `broom` and `tidyverse`.


Join this workshop meeting on Zoom by clicking [this link](https://us02web.zoom.us/j/87192854756?pwd=eTE5VnpWY2N4Rk1LVnRZdlBGdzdsdz09)


> **Lisa DeBruine** is a professor of psychology at the University of Glasgow School of Psychology and Neuroscience. She is a founding member and current Associate Director of the Psychological Science Accelerator, a member of the APA Open Science and Methodology Committee, a local lead for the UK Reproducibility Network, a member of the ORCiD Researcher Advisory Council, and a member of the psyTeachR team for reproducible research educational resources.You can read more about Lisa and her work on [her personal website](https://debruine.github.io/).



### Materials

The materials used in the workshop are on [Lisa's Github]( https://debruine.github.io/data-sim-workshops/).

The RMarkdown (Rmd) file she will be working with is linked from there at https://raw.githubusercontent.com/debruine/data-sim-workshops/master/inst/stubs/faux-stub.Rmd) 
