---
title: "NSC-R Tidy Tuesday"
description: |
  Improve your R skills in entertaining, inspiring and supportive sessions presented by your colleagues.
author:
  - name: Sam Langton
    url: https://nscr.nl/en/medewerker/sam-langton/
date: 01-11-2022
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The NSC-R Tidy Tuesday workshop sessions are inspired by the [Tidy Tuesday](https://www.tidytuesday.com/) initiative, which is aimed at providing a safe and supportive forum for individuals to practice their data processing and visualization skills in R while working with real-world data. 

Sam Langton will demonstrate some foundational R skills using a [Tidy Tuesday dataset](https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-12-21/starbucks.csv) on the nutritional (or not so nutritional) content of Starbucks drinks. If you'd like to learn more about basic wrangling and visualization in R, then come along and listen.

Join this workshop *Tuesday January 11, 2022 at 13:00* on Zoom by clicking [this link](https://us02web.zoom.us/j/86851126863?pwd=LzM5bU42Y0crRnJoRGtTWWExUHNSdz09)


*Sam* is a postdoc researcher on the evidence-based policing programme at the NSCR. His research focuses on describing and explaining the spatial and temporal patterning of police demand. Sam is interested in promoting open science in criminology, particularly through open data and sharing his knowledge (and struggles) in R.

### Materials

- The [slides (PDF)](../../../tidytuesday/11jan2022/presentation.pdf) of Sam's presentation.
- The [script (R)](../../../tidytuesday/11jan2022/script.R) that Sam worked through.
- The [plot (PNG)](../../../tidytuesday/11jan2022/starbucks_plot.png) that was created by the script.