---
title: "Tidy Tuesday Reading Club"
description: |
  Participate in dynamic, interactive and engaging reading group sessions to explore the world of data analysis.
author:
  - name: Harrie Jonkman
    url: https://harriejonkman.nl/
date: 02-20-2024
output:
  distill::distill_article:
    self_contained: false
---

The NSC-R Tidy Tuesday workshop sessions draw their inspiration from the Tidy Tuesday initiative, a dedicated platform aimed at fostering a secure and supportive environment for individuals seeking to hone their data processing and visualization skills in R, all while working with real-world data.

This workshop will be the fourth one in the Reading Club format. For details about this format, please read [the post of November 14](https://nscrweb.netlify.app/posts/2023-11-14-nsc-r-workshop-ros/). You can keep up to date with the material for each session via the corresponding [GitHub repository](https://github.com/langtonhugh/regression_book_nscr) or via the [Reading Club Notebook](https://rosnotebook.netlify.app/) maintained by Harrie Jonkman.

This workshop will be chaired by Harrie Jonkman. In this session, we will focus on Chapter 4 (on *Statistical inference*, pp. 49-68) of the book *Regression and Other Stories*. To make most of the workshops, we suggest you have a read (however brief!) of the chapter in advance. 

Join this session February 20, 2024 at 13:00 CET on Zoom by clicking [here](https://us02web.zoom.us/j/4539912989) and using the passcode 'NSCR'.

## Materials

You can keep up to date with the NSC-R Tidy Tuesday Reading Club materials via the corresponding [GitHub repository](https://github.com/langtonhugh/regression_book_nscr) or the [Reading Club Notebook](https://rosnotebook.netlify.app/) maintained by Harrie Jonkman. Look for chapter 4 *Statistical Inference*. The syntax you find [here](https://github.com/Jonkman1/ROS_reading_club_NSCR_notebook/blob/main/04-chapter.qmd). The presentation you find [here](https://65d336c15624edee4261215f--gleeful-bavarois-d00329.netlify.app/#/title-slide).

