---
title: "NSC-R Tidy Tuesday"
description: |
  Improve your R skills in entertaining, inspiring and supportive sessions moderated by your own colleagues.
author:
  - name: Alex Trinidad
    url: https://www.alexandertrinidad.com/
date: 01-10-2023
output:
  distill::distill_article:
    self_contained: false
# Remove the following line to publish
draft: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The NSC-R Tidy Tuesday workshop sessions are inspired by the [Tidy Tuesday](https://www.tidytuesday.com/) initiative, which was aimed at providing a safe and supportive forum for individuals to practice their data processing and visualization skills in R while working with real-world data.





Join this workshop meeting on Zoom by clicking [this link](https://us02web.zoom.us/j/81146395699?pwd=cG5FNWxZRC9aOUhxV2s0UUVXMW9EQT09)


> **Alex Trinidad** a postdoctoral researcher and lecturer at the Institute of Sociology and Social Psychology ([ISS](https://iss-wiso.uni-koeln.de/en)) at the University of Cologne. I am also a research fellow for the [Crime Events in Context](https://nscr.nl/en/research-area/crime-events-in-context/) research group at the Netherlands Institute for the Study of Crime and Law Enforcement ([NSCR](https://nscr.nl/en/about-us/organisation/fellows/)) and for the [Crim-Ap](https://www.ehu.eus/en/web/dms/equipo) research group at the University of the Basque Country UPV/EHU.



### Materials

Materials for the workshop will be available here.

