---
title: "Using R package distill to build websites"
description: |
  How to use the R package distill to build websites (like this one) 
author: 
  - name: Harrie Jonkman
    url: www.harriejonkman.nl/
date: 12-07-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[Distill](https://rstudio.github.io/distill/) is a package built on and for `RMarkdown`, the ecosystem of packages for creating computational documents in R. 

The goal of the `distill` package is to provide an output format optimized for online scientific and technical communication. The `distill`-R package provides HTML output formats for R Markdown documents. With the use of `distill` you can make articles, blogs and websites. 

The goal of the developers of distill was to create a platform to help scientists harness the benefits of modern HTML-based communication, which digital designers and journalists have been using to create interactive and engaging articles that meet readers where they are: online.

In this workshop you are introduced to this package. You learn how to build your own website and blog, how to place it on GitHub and deploy it for free by using Netlify. Harrie Jonkman and the NSC-R team members developed a website for the NSC-R workshops by using distill (you are reading it right now).  


### More information

- A very accessible description of how to use `distill` to build websitres is [Building a distill website](https://lisalendway.netlify.app/posts/2020-12-09-buildingdistill/?utm_source=dlvr.it&utm_medium=facebook) by by Liza Lendway.

- Another description of how to build websites with distill is [Building a blog with distill](https://themockup.blog/posts/2020-08-01-building-a-blog-with-distill/), targeted. 

- `distill` was created by people at R Studio. This is [RStudio's official website link on distill](https://rstudio.github.io/distill/)

- You could also check out [RStudio's new developments on distill](https://www.rstudio.com/blog/distill/)





> [Harrie Jonkman](https://www.harriejonkman.nl)is a senior researcher at the [Verwey Jonker Institute](https://www.verwey-jonker.nl/). He works in the field of cognitive and social development of children and youngsters in relation to the contexts in which they grow up (family, school, friends, community and country). Recently he edited with David Farrington and Frederick Groeger-Roth [Delinquency and Substance Use in Europe. Understanding Risk and Protective Factors](https://link.springer.com/book/10.1007/978-3-030-58442-9). He also finished recently the open-source book [Terugschrijven](http://www.harriejonkman.nl/wp-content/uploads/2021/05/Terugschrijven_def.pdf) on knowledge, development and democracy. He is interested in open-source data analysis and has his blog [Harrie's Hoekje](http://www.harriejonkman.nl/HarriesHoekje/) on this topic.



