---
title: "Creating web applications with Shiny (1/2)"
description: |
  Learn how to make interactive tables, graphs and text from data.
author:
  - name: Nick van Doormaal
    url: https://www.linkedin.com/in/nick-van-doormaal-9213a7a2/
date: 03-17-2022
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

In a two-sessions workshop, Nick van Doormaal will demonstrate how to use the `shiny` package to create interactive web applications. Note that this is the first session of a two-sesssion workshop. This first session will be a basic introduction on the different components of a shiny app. In the second session (on Thursday March 31) we explore into more depth how 'reactivity' works, an important component of most shiny apps.

For inspiration, you may want to spend a few minutes viewing some [fun apps](https://www.rstudio.com/blog/3-fun-shiny-apps-for-your-long-labor-day-weekend/) made with `shiny`, or [this `shiny` gallery](https://shiny.rstudio.com/gallery/).

To prepare for the workshop, you could install these two R packages (just copy and paste this line into your R Studio Editor and run it)

install.packages(c("tidyverse", "shiny"))


> **Nick van Doormaal** is a former PhD candidate at the NSCR and currently a data analyst at the environmental service of the province of Gelderland. He got into R during his MSc thesis and internship and has been using R ever since.

Join this workshop meeting on Zoom by clicking [this link](
https://us02web.zoom.us/j/87228936745?pwd=NTcrU1R0ZjE4c3FHUkNFVnE3NVBFdz09)

### Materials

### Materials

On Nick's GitHub repository [nscr-shiny-workshop](https://github.com/nvdoormaal/nscr-shiny-workshop) you can find the data and the R script that documents the development that Nick demonstrated during the second workshop on Thursday March 31. 


