---
title: "NSC-R Tidy Tuesday"
description: |
  Improve your R skills in entertaining, inspiring and supportive sessions moderated by your own colleagues.
author:
  - name: Alex Trinidad
    url: https://www.alexandertrinidad.com/
date: 02-21-2023
output:
  distill::distill_article:
    self_contained: false
# Remove the following line to publish
draft: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The NSC-R Tidy Tuesday workshop sessions are inspired by the [Tidy Tuesday](https://www.tidytuesday.com/) initiative, which was aimed at providing a safe and supportive forum for individuals to practice their data processing and visualization skills in R while working with real-world data.

In this workshop, Alex Trinidad will show how to write your own R functions. This helps automating your work and making your R scripts cleaner, shorter and easier to maintain.

 

Join this workshop meeting on Zoom by clicking [this link](https://us02web.zoom.us/j/81447063453?pwd=SEg3UU4yc2xoMVp2R3FGWWtCSjdLUT09)


> **Alex Trinidad** is a postdoctoral researcher and lecturer at the Institute of Sociology and Social Psychology (ISS) at the University of Cologne, and a research fellow for the Crime Events in Context research group at the NSCR and for the Crim-Ap research group at the University of the Basque Country UPV/EHU. He is also a member of the NSC-R Workshops Team.


### Materials

- [Here](https://github.com/alexandertrinidad/nsc_r_workshop_21_02_2023) you will find the R syntax to replicate the session. 
