---
title: "[Topic name | NSC-R Tidy Tuesday]"
description: |
  [Brief description of the contents of the session | Improve your R skills in entertaining, inspiring and supportive sessions moderated by your own colleagues.]
author:
  - name: Name Surname
    url: [URL]
date: [dd-mm-yyyy]
output:
  distill::distill_article:
    self_contained: false
# Remove the following line to publish
draft: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<!-- 1. Description --> 

<!-- 1.1. Follow this structure for regular sessions --> 
[BRIEF DESCRIPTION OF THE TOPIC (e.g. Much information is stored as free-text. Free-text is weakly structured and therefore hard to extract and organize. This workshop will explore some elements of working with free-text data in R, principally how it can be prepared and transformed to be used with machine learning algorithms.)]

<!-- 1.2. Follow this structure for Tidy Tuesday sessions --> 
The NSC-R Tidy Tuesday workshop sessions are inspired by the [Tidy Tuesday](https://www.tidytuesday.com/) initiative, which was aimed at providing a safe and supportive forum for individuals to practice their data processing and visualization skills in R while working with real-world data.

The [dataset](URL) for this Tidy Tuesday is about [TOPIC]! [PRESENTER'S NAME](URL) explores the following research questions: "[RESEARCH QUESTION 1]" and "[RESEARCH QUESTION 2]" Feel free to explore these questions yourselves and share your experience with us. 

<!-- 2. (OPTIONAL) Additional information --> 
[ADDITIONAL INFORMATION FOR THE SESSION (e.g. To prepare for the workshop, you may want to install a few R packages (just copy and paste these lines into your R Studio Editor and run them)]:

<!-- 3. Zoom link. Remove the following line after adding the materials of the session --> 
Join this workshop meeting on Zoom by clicking [this link](https://us02web.zoom.us/j/85477754782?pwd=cExxK2NCSFVWdERVcERMMVg3WjFCdz09)

<!-- 4. Bio --> 
> [INSERT HERE A SHORT BIO OF THE PRESENTER]

<!-- 5. Materials --> 
### Materials

-   The [script (R)](URL) that [PRESENTER'S NAME] worked through.
-   [ADDITIONAL MATERIAL](URL)

To download files from GitHub you can:

1.    Download all files compressed in a `ZIP`. To do this, go to the repository and click on the green `code` button, then select `download ZIP`.
2.    Download a specific file. To do this, select the desired file in the repository and click on the `raw` button. Then right click on the new page and select `save as`. Don't forget to put the proper extension in the save name, like `.R` or `.Rmd`.