---
title: "Introduction to the tidyverse"
description: |
  Introduction to the tidyverse collection of packages.
author: 
  - name: Sam Langton
    url: https://nscr.nl/medewerker/sam-langton/
date: 10-12-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This workshop covered the basics of the tidyverse – a collection of packages in R which can be used to import, tidy, transform and visualise data. The material is suitable for people with very little experience in R, but also seasoned R users who have not yet delved into the tidyverse. The skills covered were foundational and generic to almost any research project. The workshop centred around a demonstration which tackles a realistic, ‘messy’ dataset about animal rescue incidents dealt with by the London Fire Brigade.

> *Sam Langton* is a postdoc researcher on the evidence-based policing programme at the NSCR. His research focuses on describing and explaining the spatial and temporal patterning of police demand. Sam is interested in promoting open science in criminology, particularly through open data and sharing his knowledge (and struggles) in R.

### Materials

- You can find the material for this workshop on [GitHub](https://github.com/langtonhugh/rss_r) or alternatively on [Dropbox](https://www.dropbox.com/sh/wfq4og1dig01p9q/AAA003pRT2Qxa3BK35pBANP1a?dl=0).


