---
title: "NSC-R Tidy Tuesday"
description: |
  Improve your R skills in entertaining, inspiring and supportive sessions moderated by your own colleagues.
author:
  - name: Alex Trinidad
    url: https://www.alexandertrinidad.com/
date: 05-03-2022
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The NSC-R Tidy Tuesday workshop sessions are inspired by the [Tidy Tuesday](https://www.tidytuesday.com/) initiative, which was aimed at providing a safe and supportive forum for individuals to practice their data processing and visualization skills in R while working with real-world data. 

The [dataset](https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-03-29/readme.md) for this Tidy Tuesday is about Collegiate Sports in US. **Alex Trinidad** explores how revenue and expenditure are distributed in sports. He also looks at the differences in sport revenues and expenditures between men and women.    

Join this workshop meeting on Zoom by clicking [this link](https://us02web.zoom.us/j/86710142987?pwd=L2o3dDdnZk5OSlJUOFlyNktMMDlpUT09)

> **Alex Trinidad** is a postdoctoral researcher/ lecturer at the Institute of Sociology and Social Psychology (ISS) at the University of Cologne, Germany. He is also a research fellow at the Netherlands Institute for the Study of Crime and Law Enforcement (NSCR). His interest in spatial analysis began when he started his PhD, exploring the spatial distribution of juvenile delinquency and the contextual factors associated with it. It was also during his PhD that he began his journey with R. 


### Materials & Instructions

- The [script (R)](https://github.com/alexandertrinidad/tidy_tuesday/blob/main/tt_nscr_03_05.R) that Alex worked with. Please feel free to copy and paste the syntax in an new R script. If you run the whole script be aware that some errors will come up. Those are made on purpose, and the solution is in the next lines. If the error is due to a lack of package, check some of the comments (#) in the script, and install the needed package. 
- 


