---
title: "NSC-R Tidy Tuesday"
description: |
  Improve your R skills in entertaining, inspiring and supportive sessions moderated by your own colleagues.
author:
  - name: Asier Moneva
    url: https://nscr.nl/en/medewerker/asier-moneva/
date: 04-19-2022
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The NSC-R Tidy Tuesday workshop sessions are inspired by the [Tidy Tuesday](https://www.tidytuesday.com/) initiative, which was aimed at providing a safe and supportive forum for individuals to practice their data processing and visualization skills in R while working with real-world data.

The [dataset](https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-04-12/indoor_pollution.csv) for this Tidy Tuesday is about indoor air pollution! **Asier Moneva** explores the following research question: “How have trends in deaths due to household air pollution from solid fuels evolved in the EU countries over the last 30 years?” Feel free to explore this question yourselves and share your experience with us.

Join this workshop meeting on Zoom by clicking [this link](https://us02web.zoom.us/j/82954366080?pwd=bzdpSzRkNktzVkZSOEdNUTlSdTNmdz09)



> **Asier Moneva** is a postdoc at the NSCR and The Hague University of Applied Sciences with a background in criminology. He started specializing in crime analysis with R during his master's degree and has since developed an interest in open science.

### Materials

-   The R script that Asier worked through is in [this GitHub repository](https://github.com/amoneva/tidy_tuesday/blob/main/week15_air_pollution.Rmd) that Asier worked through.

### How to download files from GitHub

To download files from GitHub you can:

`Clone` the repository to create a local copy in your computer. To clone a repository, follow the instructions [here](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository).

Alternatively, you can:

1.    Download all files compressed in a `ZIP`. To do this, go to the repository and click on the green `code` button, then select `download ZIP`. Unzip the downloaded file into a folder on your local computer.
2.    Download a specific file. To do this, select the desired file in the repository and click on the `raw` button. Then right click on the new page and select `save as`. Don't forget to put the proper extension in the save name, like `.R` or `.Rmd`.
