---
title: "NSC-R Walk-In Hour"
description: |
  Drop by and meet our team to discuss any R-related issues  
author:
  - name: NSC-R Workshops Team
    url: 
date: 04-21-2023
output:
  distill::distill_article:
    self_contained: false
# Remove the following line to publish
draft: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Friday April 21, 13:00-14:00 (NSCR Colloquium room and [on Zoom](https://us02web.zoom.us/j/82560454922?pwd=cUpKdkdvWjJ5dWVvNTRCUFBPbHNRUT09))**

The NSC-R Walk-In Hour is a recurring event where you can drop by and meet our team to discuss any R-related issues. Whether you have urgent questions, want to work on your R project, or simply want to socialize with fellow R enthusiasts, you are welcome to join!

The Walk-In Hour takes place bi-weekly, normally on Fridays between 13:00 and 14:00. It has a hybrid format, with an in-person meeting in the Colloquium room at the NSCR and an open online Zoom session running in parallel. 

There is no need to register. Simply bring your laptop and join us in person or online.

If you have a private R-related query, you can contact us via e-mail, Zoom private chat, or phone. There will be an NSC-R member present both online and offline to assist.

Join this event on Zoom by clicking [this link](https://us02web.zoom.us/j/82560454922?pwd=cUpKdkdvWjJ5dWVvNTRCUFBPbHNRUT09)


> The *NSC-R Workshops Team* organizes workshops, courses and other events related to R. The members are Wim Bernasco, Sam Langton, Asier Moneva, Abby Onencan, Alex Trinidad, Danielle van Westbroek-Stibbe and Franziska Yasrebi-de Kom. 




